openapi: 3.0.3
info:
  title: Forem API V1
  version: 1.0.0
  description: |-
    Access Forem articles, users and other resources via API.
            For a real-world example of Forem in action, check out [DEV](https://www.dev.to).
            All endpoints can be accessed with the 'api-key' header and a accept header, but
            some of them are accessible publicly without authentication.

            Dates and date times, unless otherwise specified, must be in
            the [RFC 3339](https://tools.ietf.org/html/rfc3339) format.
servers:
  - url: https://dev.to/api
    description: Production server
security:
  - api-key: []
paths:
  /articles:
    $ref: paths/articles.yaml
  /articles/latest:
    $ref: paths/articles_latest.yaml
  /articles/{id}:
    $ref: paths/articles_{id}.yaml
  /articles/{username}/{slug}:
    $ref: paths/articles_{username}_{slug}.yaml
  /articles/me:
    $ref: paths/articles_me.yaml
  /articles/me/published:
    $ref: paths/articles_me_published.yaml
  /articles/me/unpublished:
    $ref: paths/articles_me_unpublished.yaml
  /articles/me/all:
    $ref: paths/articles_me_all.yaml
  /articles/{id}/unpublish:
    $ref: paths/articles_{id}_unpublish.yaml
  /comments:
    $ref: paths/comments.yaml
  /comments/{id}:
    $ref: paths/comments_{id}.yaml
  /display_ads:
    $ref: paths/display_ads.yaml
  /display_ads/{id}:
    $ref: paths/display_ads_{id}.yaml
  /display_ads/{id}/unpublish:
    $ref: paths/display_ads_{id}_unpublish.yaml
  /follows/tags:
    $ref: paths/follows_tags.yaml
  /followers/users:
    $ref: paths/followers_users.yaml
  /organizations/{username}:
    $ref: paths/organizations_{username}.yaml
  /organizations/{username}/users:
    $ref: paths/organizations_{username}_users.yaml
  /organizations/{username}/articles:
    $ref: paths/organizations_{username}_articles.yaml
  /pages:
    $ref: paths/pages.yaml
  /pages/{id}:
    $ref: paths/pages_{id}.yaml
  /podcast_episodes:
    $ref: paths/podcast_episodes.yaml
  /profile_images/{username}:
    $ref: paths/profile_images_{username}.yaml
  /reactions/toggle:
    $ref: paths/reactions_toggle.yaml
  /reactions:
    $ref: paths/reactions.yaml
  /readinglist:
    $ref: paths/readinglist.yaml
  /tags:
    $ref: paths/tags.yaml
  /users/me:
    $ref: paths/users_me.yaml
  /users/{id}:
    $ref: paths/users_{id}.yaml
  /users/{id}/unpublish:
    $ref: paths/users_{id}_unpublish.yaml
  /users/{id}/suspend:
    $ref: paths/users_{id}_suspend.yaml
  /admin/users:
    $ref: paths/admin_users.yaml
  /videos:
    $ref: paths/videos.yaml
components:
  securitySchemes:
    api-key:
      type: apiKey
      name: api-key
      in: header
      description: >-
        API Key authentication.


        Authentication for some endpoints, like write operations on the

        Articles API require a DEV API key.


        All authenticated endpoints are CORS disabled, the API key is intended
        for non-browser scripts.


        ### Getting an API key


        To obtain one, please follow these steps:

          - visit https://dev.to/settings/extensions
          - in the "DEV API Keys" section create a new key by adding a
            description and clicking on "Generate API Key"

            ![obtain a DEV API Key](https://user-images.githubusercontent.com/37842/172718105-bd93664e-76e0-477d-99c4-265dda0b06c5.png)

          - You'll see the newly generated key in the same view
            ![generated DEV API Key](https://user-images.githubusercontent.com/37842/172718151-e7fe26a0-9937-42e8-96c6-333acdab9e49.png)
